### ISSUE TITLE
クロージャでpanicが発生する

### ISSUE THREAD

**Issue by hidekuno** [hidekuno/go-scheme#104]
正解は40
```
[kunohi@centos7-dev-docker src]$ go run lisp_main.go 
scheme.go>  (define (testf x) (lambda () (* x 10)))
testf
scheme.go>  (define (foo x) (testf (* 2 x)))
foo
scheme.go>  ((foo 2))
panic: runtime error: index out of range

goroutine 1 [running]:
scheme.evalTailRecursion(0xc00000e590, 0xc0000765a0, 0xc0000160f6, 0x5, 0xc00000a170, 0x1, 0x1, 0x40805b, 0x5c6140)
	/home/kunohi/go-scheme/src/scheme/lisp.go:862 +0x61f
scheme.(*Function).Execute(0xc00009e000, 0xc00000a3d0, 0x1, 0x1, 0xc00000e580, 0x0, 0x0, 0xc0000a0120, 0xc000045710)
	/home/kunohi/go-scheme/src/scheme/lisp.go:524 +0x24b
scheme.eval(0x519f00, 0xc0000768d0, 0xc00000e580, 0x3, 0xc00000a2f0, 0x1, 0x1)
	/home/kunohi/go-scheme/src/scheme/lisp.go:834 +0x68b
scheme.(*Function).Execute(0xc00009e070, 0xc00000a450, 0x1, 0x1, 0xc00000e420, 0x0, 0x0, 0x5c6140, 0x4e4560)
	/home/kunohi/go-scheme/src/scheme/lisp.go:527 +0x165
scheme.eval(0x519f00, 0xc0000769c0, 0xc00000e420, 0x0, 0x0, 0x0, 0x0)
	/home/kunohi/go-scheme/src/scheme/lisp.go:834 +0x68b
scheme.eval(0x519f00, 0xc0000769f0, 0xc00000e420, 0x519f00, 0xc0000769f0, 0x6, 0x0)
	/home/kunohi/go-scheme/src/scheme/lisp.go:825 +0x361
scheme.DoCoreLogic(0xc000016140, 0x9, 0xc00000e420, 0x4ffda0, 0x1, 0xc000016140, 0x9)
	/home/kunohi/go-scheme/src/scheme/lisp.go:896 +0xa4
scheme.repl(0xc00000c010, 0xc00000e420)
	/home/kunohi/go-scheme/src/scheme/lisp.go:957 +0x39f
scheme.DoInteractive()
	/home/kunohi/go-scheme/src/scheme/lisp.go:928 +0x8c
main.main()
	/home/kunohi/go-scheme/src/lisp_main.go:16 +0x25
exit status 2
[kunohi@centos7-dev-docker src]$ 
```

**Comment by hidekuno** [comment]
このパターンでも落ちる
```
[kunohi@centos7-dev-docker src]$ go run lisp_main.go                                                                                      
scheme.go>  (define (testf x) (lambda () (* x 10)))                                                                                       
testf                                                                                                                                     
scheme.go>  (testf 10)                                                                                                                    
panic: runtime error: index out of range                                                                                                  
                                                                                                                                          
goroutine 1 [running]:                                                                                                                    
scheme.evalTailRecursion(0xc00000e4f0, 0xc00005e5a0, 0xc000016130, 0x5, 0xc00000a170, 0x1, 0x1, 0x40805b, 0x5c6140)                       
        /home/kunohi/go-scheme/src/scheme/lisp.go:862 +0x61f                                                                              
scheme.(*Function).Execute(0xc000088000, 0xc00000a2d0, 0x1, 0x1, 0xc00000e420, 0x0, 0x0, 0x2, 0xc00000a2c0)                               
        /home/kunohi/go-scheme/src/scheme/lisp.go:524 +0x24b                                                                              
scheme.eval(0x519f00, 0xc00005e690, 0xc00000e420, 0x519f00, 0xc00005e690, 0x4, 0x0)                                                       
        /home/kunohi/go-scheme/src/scheme/lisp.go:834 +0x68b                                                                              
scheme.DoCoreLogic(0xc000016150, 0xa, 0xc00000e420, 0x4ffda0, 0x1, 0xc000016150, 0xa)                                                     
        /home/kunohi/go-scheme/src/scheme/lisp.go:896 +0xa4                                                                               
scheme.repl(0xc00000c010, 0xc00000e420)                                                                                                   
        /home/kunohi/go-scheme/src/scheme/lisp.go:957 +0x39f                                                                              
scheme.DoInteractive()                                                                                                                    
        /home/kunohi/go-scheme/src/scheme/lisp.go:928 +0x8c                                                                               
main.main()                                                                                                                               
        /home/kunohi/go-scheme/src/lisp_main.go:16 +0x25                                                                                  
exit status 2                                                                                                                             
[kunohi@centos7-dev-docker src]$                                                                                                          
```

**Comment by hidekuno** [comment]
rust版では空リストチェックを行なっている。
```
   fn parse_tail_recurcieve(&self, exp: &[Expression]) -> bool {
        let mut n = 0;
        for e in exp {
            if let Expression::List(l) = e {
                if 0 == l.len() {
                    continue;
                }
                if let Expression::Symbol(s) = &l[0] {
```
