### ISSUE TITLE
load-file関数の安全性を向上する(頑強にする)

### ISSUE THREAD

**Issue by hidekuno** [hidekuno/go-scheme#112]
ディレクトリを読むと固まる
```
NPC106:src kunohi$ go run lisp_main.go 
scheme.go>  (load-file "/Users/kunohi/tmp")
```

**Comment by hidekuno** [comment]
バイナリファイルはこけない
```
scheme.go>  (load-file "/Users/kunohi/tmp/a.out")
nil
scheme.go>  (quit)
```

**Comment by hidekuno** [comment]
読み取り権限のないファイルはコケる
```
scheme.go>  (load-file "/etc/sudoers~orig")
panic: open /etc/sudoers~orig: permission denied

goroutine 1 [running]:
scheme.BuildFunc.func56(0xc0000880b0, 0x1, 0x1, 0xc0000821d0, 0x0, 0x0, 0x0, 0x0)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:1829 +0x487
scheme.(*BuildInFunc).Execute(...)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:470
scheme.eval(0x1127a40, 0xc00008a1e0, 0xc0000821d0, 0x1127a40, 0xc00008a1e0, 0x4, 0x0)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:831 +0x727
scheme.DoCoreLogic(0xc0000a6000, 0x1f, 0xc0000821d0, 0x1106f60, 0x1, 0xc0000a6000, 0x1f)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:899 +0x181
scheme.repl(0xc000078000, 0xc0000821d0)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:960 +0x393
scheme.DoInteractive()
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:931 +0x8d
main.main()
	/Users/kunohi/git/go-scheme/src/lisp_main.go:16 +0x25
exit status 2
NPC106:src kunohi$ 
```

**Comment by hidekuno** [comment]
読み取り権限のないファイルに対応
```
scheme.go>  (load-file "/etc/shadow")
System Panic:  (lisp.go:1803)
scheme.go>  
```
