### ISSUE TITLE
()を入力するとpanic

### ISSUE THREAD

**Issue by hidekuno** [hidekuno/go-scheme#23]
```
[kunohi@centos7-dev-docker src]$ go run lisp.go
scheme.go>  ()
panic: runtime error: index out of range

goroutine 1 [running]:
main.eval(0x548300, 0xc42007a240, 0xc42000e3d0, 0x548300, 0xc42007a240, 0x2, 0x0)
	/home/kunohi/go-scheme/src/lisp.go:616 +0xb7d
main.do_core_logic(0xc4200140bc, 0x2, 0xc42000e3d0, 0x400, 0xc4200140bc, 0x2, 0x0)
	/home/kunohi/go-scheme/src/lisp.go:667 +0xa8
main.do_interactive()
	/home/kunohi/go-scheme/src/lisp.go:693 +0x330
main.main()
	/home/kunohi/go-scheme/src/lisp.go:1217 +0x25
exit status 2
[kunohi@centos7-dev-docker src]$ 
```

**Comment by hidekuno** [comment]
```
diff --git a/src/lisp.go b/src/lisp.go
index d3def36..c6eef17 100644
--- a/src/lisp.go
+++ b/src/lisp.go
@@ -611,8 +611,10 @@ func eval(sexp Expression, env *SimpleEnv) (Expression, error) {
                        return sexp, nil
                }
        } else if sl, ok := sexp.(*List); ok {
+               if len(sl.Value) == 0 {
+                       return sexp, nil
+               }
                v := sl.Value
-
                if _, ok := v[0].(*Symbol); ok {
                        proc, err := eval(v[0], env)
                        if err != nil {
```
