### ISSUE TITLE
キャストチェック忘れ

### ISSUE THREAD

**Issue by hidekuno** [hidekuno/go-scheme#93]
```
1525                 } else if l, ok := exp[0].(*List); ok {
1526                         if len(l.Value) < 1 {
1527                                 return nil, NewRuntimeError("E1007", strconv.Itoa(len(exp)))
1528                         }
1529                         key = l.Value[0].(*Symbol)  -> ⭐️
1530                         e = NewFunction(env, NewList(l.Value[1:]), exp[1:], key.Value)
```

**Comment by hidekuno** [comment]
lisp_test.goも修正する

**Comment by hidekuno** [comment]
```
scheme.go>  (let ((1 0)(a 20)) a)     
panic: interface conversion: scheme.Expression is *scheme.Integer, not *scheme.Symbol

goroutine 1 [running]:
scheme.BuildFunc.func45(0xc000046150, 0x2, 0x3, 0xc0000101f0, 0xc00008e300, 0x0, 0x0, 0x3)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:1658 +0xe18
scheme.(*BuildInFunc).Execute(...)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:470
scheme.eval(0x1127a20, 0xc00008e2d0, 0xc0000101f0, 0x1127a20, 0xc00008e2d0, 0xe, 0x0)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:837 +0x741
scheme.DoCoreLogic(0xc0000120e0, 0x15, 0xc0000101f0, 0x1106f20, 0x1, 0xc0000120e0, 0x15)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:914 +0x181
scheme.repl(0xc000084000, 0xc0000101f0)
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:975 +0x393
scheme.DoInteractive()
	/Users/kunohi/git/go-scheme/src/scheme/lisp.go:946 +0x8d
main.main()
	/Users/kunohi/git/go-scheme/src/lisp_main.go:16 +0x25
exit status 2
NPC106:src kunohi$
```

**Comment by hidekuno** [comment]
owari
